version: '3.8'

services:
  spring-api:
    build: .
    container_name: springboot-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
